"""
Generates a downloadable PDF report summarising a resume's AI evaluation.
"""

from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def generate_resume_report(student_name: str, file_name: str, resume_quality_score: int,
                             ats_compatibility_score: int, missing_sections: list,
                             detected_issues: list, improvement_suggestions: str,
                             skills: list) -> BytesIO:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=30 * mm, bottomMargin=20 * mm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleStyle", parent=styles["Title"], textColor=colors.HexColor("#2563EB"), fontSize=20)
    heading_style = ParagraphStyle("HeadingStyle", parent=styles["Heading2"], textColor=colors.HexColor("#333333"), spaceBefore=14, spaceAfter=6)
    body_style = ParagraphStyle("BodyStyle", parent=styles["BodyText"], fontSize=10.5, leading=15)
    meta_style = ParagraphStyle("MetaStyle", parent=styles["BodyText"], fontSize=9.5, textColor=colors.HexColor("#888888"))

    elements = []

    elements.append(Paragraph("AI-CROS Resume Evaluation Report", title_style))
    elements.append(Paragraph(f"Student: {student_name} &nbsp;&nbsp;|&nbsp;&nbsp; File: {file_name}", meta_style))
    elements.append(Spacer(1, 16))

    # Score summary table
    score_table = Table(
        [["Resume Quality Score", "ATS Compatibility Score"], [f"{resume_quality_score} / 100", f"{ats_compatibility_score} / 100"]],
        colWidths=[240, 240],
    )
    score_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EEF3FF")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#2563EB")),
        ("FONTSIZE", (0, 0), (-1, 1), 12),
        ("FONTSIZE", (0, 1), (-1, 1), 20),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ("TOPPADDING", (0, 1), (-1, 1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD")),
    ]))
    elements.append(score_table)
    elements.append(Spacer(1, 20))

    if missing_sections:
        elements.append(Paragraph("Missing Sections", heading_style))
        for section in missing_sections:
            elements.append(Paragraph(f"• {section.capitalize()}", body_style))

    if detected_issues:
        elements.append(Paragraph("Detected Issues", heading_style))
        for issue in detected_issues:
            elements.append(Paragraph(f"• {issue}", body_style))

    elements.append(Paragraph("Improvement Suggestions", heading_style))
    elements.append(Paragraph(improvement_suggestions or "No suggestions available.", body_style))

    if skills:
        elements.append(Paragraph("Extracted Skills", heading_style))
        skill_text = ", ".join(s["skill_name"] if isinstance(s, dict) else s for s in skills)
        elements.append(Paragraph(skill_text, body_style))

    elements.append(Spacer(1, 24))
    elements.append(Paragraph("Generated by AI-CROS — AI-Powered Career Readiness & Opportunity Sourcing System", meta_style))

    doc.build(elements)
    buffer.seek(0)
    return buffer